steps:
  - name: 'gcr.io/stockfactsproject/ndaqfactsdockerwithdeps'
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/stockfactsproject', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/[PROJECT-ID]/stockfactsproject"]
images: ['gcr.io/$PROJECT_ID/stockfactsproject']
