steps:
  - name: 'gcr.io/stockfactsproject/ndaqfactsdockerwithdeps'
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/stockfactsproject', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/stockfactsproject"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment
      - stockfacts
      - springbootndaqfacts=gcr.io/stockfactsproject/stockfactsproject
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=stockfactsapp-cluster'
#images: ['gcr.io/$PROJECT_ID/stockfactsproject']
